pipeline {
    agent any

    environment {
        IMAGE_NAME = 'vinothraja2405/flask-jenkins-app'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/Vinothraja2405/Jenkins-CI-CD-for-Flask-App-with-Docker.git'
            }
        }

        stage('Install Dependencies and Test') {
            steps {
                sh 'docker run --rm -v $PWD:/app -w /app python:3.9 bash -c "pip install -r app/requirements.txt && pytest"'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME} ."
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${IMAGE_NAME}
                    """
                }
            }
        }

        stage('Cleanup') {
            steps {
                sh "docker rmi ${IMAGE_NAME} || true"
            }
        }
    }
}
