pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds') // set in Jenkins credentials
        IMAGE_NAME = 'vinothraja2405/flask-jenkins-app'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Vinothraja2405/Jenkins-CI-CD-for-Flask-App-with-Docker.git'

            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest test/test_app.py'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                    sh 'docker push $IMAGE_NAME'
                }
            }
        }

        stage('Cleanup') {
            steps {
                sh 'docker rmi $IMAGE_NAME || true'
            }
        }
    }
}
