pipeline {
    agent any

    environment {
        IMAGE_NAME = 'vinothraja2405/flask-jenkins-app'
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/Vinothraja2405/Jenkins-CI-CD-for-Flask-App-with-Docker.git'
            }
        }

        stage('Install Dependencies and Test') {
            steps {
                script {
                    docker.image('python:3.9').inside {
                        sh 'pip install -r app/requirements.txt'
                        sh 'pytest'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    docker.withRegistry('', 'dockerhub-creds') {
                        sh 'docker push $IMAGE_NAME'
                    }
                }
            }
        }

        stage('Cleanup') {
            steps {
                sh 'docker rmi $IMAGE_NAME || true'
            }
        }
    }
}
